In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. Create a NumPy array of integers from 1 to 10 (inclusive).
arr = np.array(np.arange(1,11))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 2. Reshape the array from the previous question into a 2x5 matrix.
arr1 = arr.reshape(2,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
# 3. Perform element-wise multiplication of two NumPy arrays:
mul1 = np.arange(1,12,2).reshape(3,2)
mul2 = np.arange(1,7).reshape(3,2)
print(mul1)
print()
print(mul2)
print()
print(mul1*mul2)

[[ 1  3]
 [ 5  7]
 [ 9 11]]

[[1 2]
 [3 4]
 [5 6]]

[[ 1  6]
 [15 28]
 [45 66]]


In [5]:
# 4. Create one multidimensional array of shape (3,4,2) and perform indexing and slicing on it.
multi_arr = np.arange(24).reshape(3, 4, 2)
print("\n3D array (3,4,2):\n", multi_arr)
print("\nElement at [1, 2, 0]:", multi_arr[1, 2, 0])
print("\nSlice [0, :, :]:\n", multi_arr[0, :, :])


3D array (3,4,2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]

Element at [1, 2, 0]: 12

Slice [0, :, :]:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [6]:
# 5. Generate a 3x3 matrix with random values between 0 and 1.
random_matrix = np.random.rand(3, 3)
print("\n3x3 Random Matrix:\n", random_matrix)


3x3 Random Matrix:
 [[0.90453325 0.33442726 0.62431432]
 [0.03651426 0.1256301  0.39357913]
 [0.16780867 0.13476587 0.33180114]]


In [7]:
# 6. Create two 2d array and perform hstack and vstack
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

h_stacked = np.hstack((x, y))
v_stacked = np.vstack((x, y))
print("\nHorizontal Stack:\n", h_stacked)
print("\nVertical Stack:\n", v_stacked)


Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
